# Generated by Django 3.0.6 on 2021-09-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.URLField(blank=True),
        ),
    ]
